### ISSUE TITLE
Replace mic icon with a brand neutral or a free mic icon

### ISSUE THREAD

**Issue by OleksiyRudenko** [OleksiyRudenko/hooli-style-popup#1]
![mic](https://github.com/OleksiyRudenko/hooli-style-popup/raw/dev/src/img/mic.png) [mic](https://github.com/OleksiyRudenko/hooli-style-popup/blob/dev/src/img/mic.png) icon is too branded.

Needs to be replaced.

**Comment by DuyguKeskek** [comment]
Hello, I want to take this and will create a pull request, thank you.

**Comment by OleksiyRudenko** [comment]
@DuyguKeskek thank you! It's all yours.
Please keep image dimensions unchanged.
PR target branch - `master` in this repo.

**Comment by vikasprashar99** [comment]
check my pr added a simple mic icon

**Comment by OleksiyRudenko** [comment]
Hi @vikasprashar99 ,
Thank you for your proposal. However I'd wait for a pr from @DuyguKeskek first.
Thank you for your understanding.

**Comment by DuyguKeskek** [comment]
Hello, the issue is fixed here : #6

**Comment by OleksiyRudenko** [comment]
Resolved by #7
