### ISSUE TITLE
Patch icons

### ISSUE THREAD

**Issue by OleksiyRudenko** [OleksiyRudenko/hooli-style-popup#2]
Icons [here](https://github.com/OleksiyRudenko/hooli-style-popup/blob/dev/src/img/hooli-apps.png) should be:
* [ ] replaced with a free alternative if used in the project (see [navigation-icons.sass](https://github.com/OleksiyRudenko/hooli-style-popup/blob/dev/src/sass/navigation-icons.sass))
* [ ] blanked out if not used in the project

Icons to replace:
![image](https://user-images.githubusercontent.com/8686631/67159730-7b6aad00-f351-11e9-8f2a-567016dcb4ea.png)
![image](https://user-images.githubusercontent.com/8686631/67159737-87ef0580-f351-11e9-8bf2-98aa856d9d93.png)

**Comment by DuyguKeskek** [comment]
Hey @OleksiyRudenko, is this issue is only about changing the icons ? I don't get what you mean by "blanked out if not used in the project". If the icons need to be changed I can take this issue too, thank you!

**Comment by OleksiyRudenko** [comment]
Those icons are all stored in a single image file. Whenever a specific icon is required it is "extracted" by the means of css properties.
Not all icons from the file are in use.
So we want those in use be replaced with something brand neutral (yet colorful and nice) and those **not** in use just replaced with transparent pixels. As a result the file won't contain any Google (or any other brand) proprietary images/icons.
Does the above make any sense to you?

**Comment by OleksiyRudenko** [comment]
We still want new icons (replacements) stay within bounding boxes of their counterparts to avoid patching the styles. So it is expected that only `./src/img/hooli-apps.png` gets changed.

**Comment by OleksiyRudenko** [comment]
@DuyguKeskek please note that it is recommended to checkout `master` before creating a branch for this issue, so that the new branch won't contain commits from your past contributions.

Optionally you may want to update your local `master` from this repo's `master` to see your past contributions in effect. Those were rebased onto `master` rather than merged into it with a merge commit.
