### ISSUE TITLE
Replace bell icon with a brand neutral or a free mic icon 

### ISSUE THREAD

**Issue by OleksiyRudenko** [OleksiyRudenko/hooli-style-popup#3]
![bell](https://github.com/OleksiyRudenko/hooli-style-popup/raw/dev/src/img/bell.jpg) [bell](https://github.com/OleksiyRudenko/hooli-style-popup/blob/dev/src/img/bell.jpg) icon is too branded.

Needs to be replaced.

**Comment by DuyguKeskek** [comment]
Hi @OleksiyRudenko, I can take this too :)

**Comment by vikasprashar99** [comment]
check my pr i have added a mic icon and i guess u wanted the same

**Comment by OleksiyRudenko** [comment]
@DuyguKeskek thank you. It would be great if you make both icons in the same style.
Please keep icon dimensions and visible part bounding box dimensions as much as possible to have the design unaffected.

**Comment by OleksiyRudenko** [comment]
@vikasprashar99 thank you for your pr. I'll take a look at it. However it would be not really nice from my side not to give a priority to a contributor who claimed the issue earlier.
Thank you for your understanding.

**Comment by DuyguKeskek** [comment]
Hello @OleksiyRudenko, the issue is fixed here: #7

**Comment by OleksiyRudenko** [comment]
Resolved by #7
