### ISSUE TITLE
Fix navbar icons positioning

### ISSUE THREAD

**Issue by OleksiyRudenko** [OleksiyRudenko/hooli-style-popup#8]
Before #7 
![image](https://user-images.githubusercontent.com/8686631/67164072-14fc8380-f37f-11e9-9eeb-b2bbe93f5fde.png)

After #7 
![image](https://user-images.githubusercontent.com/8686631/67164079-234a9f80-f37f-11e9-9d22-96ef7cc2d8b8.png)

Fix icons positioning so the icon aligned against popup position (please do not fix popup's position).

**Comment by never2average** [comment]
@OleksiyRudenko could this issue be assigned to me

**Comment by OleksiyRudenko** [comment]
@never2average thank you. It's all yours.
Please consider changing only styles related to the bell icon. Whether it is margin or padding, it is for you to decide.

**Comment by mazsam** [comment]
@OleksiyRudenko Can i take this issue?  since @never2average no progress yet

**Comment by V3dant** [comment]
![72703594_2425404107704366_4413391673338363904_n](https://user-images.githubusercontent.com/16653737/67233702-611ff480-f461-11e9-8cae-e1a891c29458.jpg)

Hey, @OleksiyRudenko since @never2average didn't respond yet I tried to fix the issue. have a look at the image if it's okay I'll go ahead and make a pull request.

**Comment by mazsam** [comment]
@V3dant I was just about to do it, okay if you are done 👍

**Comment by OleksiyRudenko** [comment]
Hi all, there is a pr #10 on the very same topic. I shall revert to you after having it reviewed.
Thank you for taking this call

**Comment by OleksiyRudenko** [comment]
@never2average , @V3dant , @mazsam thank you for your efforts.
The issue's been resolved by #10 
Thanks to @adriantirusli
